import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Box from "@/components/box/Box";
import Numbers from "@/components/numbers/Numbers";

export default function Home() {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box />
      <Numbers numbers={[100, 20, 300, 4, 5]} />
    </div>
  );
}
