import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useTranslation } from "react-i18next";
import Cookies from "js-cookie";

const languageSwitcher = [
  {
    name: "Português",
    value: "ptBR",
  },
  {
    name: "English",
    value: "en",
  },
  {
    name: "Espanhol",
    value: "es",
  },
  {
    name: "Kuduairo",
    value: "ku",
  },
];

export default function Home() {
  const { t, i18n } = useTranslation();
  return (
    <>
      <Head>
        <title>Desafio 5</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.container}>
        <h1>{t("title")}</h1>
        <h2>{t("subtitle")}</h2>
        {languageSwitcher.map((languageOption) => (
          <button
            key={languageOption.value}
            onClick={() => {
              i18n.changeLanguage(languageOption.value);
              Cookies.set("i18next", languageOption.value);
            }}
          >
            {languageOption.name}
          </button>
        ))}
      </main>
    </>
  );
}
